export const lendingStatus = () => [
  { value: "0", text: "Issued" },
  { value: "1", text: "Damaged" },
  { value: "2", text: "Misplaced" },
  { value: "3", text: "Collected" },
];

export const status = () => [
  { value: "1", text: "Active" },
  { value: "2", text: "Inactive" },
];

export const avalaibleStatus = () => [
  { value: "1", text: "Available" },
  { value: "2", text: "Not-Available" },
  { value: "3", text: "Lended" },
  { value: "4", text: "Reference Only" },
];

export const language = () => [
  { value: "1", text: "Sinhala" },
  { value: "2", text: "English" },
  { value: "3", text: "Pali" },
  { value: "4", text: "Tamail" },
  { value: "5", text: "Hindi" },
];

export const nationalities = () => [
  { value: "	1	", text: "Afghan	" },
  { value: "	2	", text: "Albanian	" },
  { value: "	3	", text: "Algerian	" },
  { value: "	4	", text: "American	" },
  { value: "	5	", text: "Andorran	" },
  { value: "	6	", text: "Angolan	" },
  { value: "	7	", text: "Anguillan	" },
  { value: "	8	", text: "Argentine	" },
  { value: "	9	", text: "Armenian	" },
  { value: "	10	", text: "Australian	" },
  { value: "	11	", text: "Austrian	" },
  { value: "	12	", text: "Azerbaijani	" },
  { value: "	13	", text: "Bahamian	" },
  { value: "	14	", text: "Bahraini	" },
  { value: "	15	", text: "Bangladeshi	" },
  { value: "	16	", text: "Barbadian	" },
  { value: "	17	", text: "Belarusian	" },
  { value: "	18	", text: "Belgian	" },
  { value: "	19	", text: "Belizean	" },
  { value: "	20	", text: "Beninese	" },
  { value: "	21	", text: "Bermudian	" },
  { value: "	22	", text: "Bhutanese	" },
  { value: "	23	", text: "Bolivian	" },
  { value: "	24	", text: "Botswanan	" },
  { value: "	25	", text: "Brazilian	" },
  { value: "	26	", text: "British	" },
  { value: "	27	", text: "British Virgin Islander	" },
  { value: "	28	", text: "Bruneian	" },
  { value: "	29	", text: "Bulgarian	" },
  { value: "	30	", text: "Burkinan	" },
  { value: "	31	", text: "Burmese	" },
  { value: "	32	", text: "Burundian	" },
  { value: "	33	", text: "Cambodian	" },
  { value: "	34	", text: "Cameroonian	" },
  { value: "	35	", text: "Canadian	" },
  { value: "	36	", text: "Cape Verdean	" },
  { value: "	37	", text: "Cayman Islander	" },
  { value: "	38	", text: "Central African	" },
  { value: "	39	", text: "Chadian	" },
  { value: "	40	", text: "Chilean	" },
  { value: "	41	", text: "Chinese	" },
  { value: "	42	", text: "Citizen of Antigua and Barbuda	" },
  { value: "	43	", text: "Citizen of Bosnia and Herzegovina	" },
  { value: "	44	", text: "Citizen of Guinea-Bissau	" },
  { value: "	45	", text: "Citizen of Kiribati	" },
  { value: "	46	", text: "Citizen of Seychelles	" },
  { value: "	47	", text: "Citizen of the Dominican Republic	" },
  { value: "	48	", text: "Citizen of Vanuatu 	" },
  { value: "	49	", text: "Colombian	" },
  { value: "	50	", text: "Comoran	" },
  { value: "	51	", text: "Congolese (Congo)	" },
  { value: "	52	", text: "Congolese (DRC)	" },
  { value: "	53	", text: "Cook Islander	" },
  { value: "	54	", text: "Costa Rican	" },
  { value: "	55	", text: "Croatian	" },
  { value: "	56	", text: "Cuban	" },
  { value: "	57	", text: "Cymraes	" },
  { value: "	58	", text: "Cymro	" },
  { value: "	59	", text: "Cypriot	" },
  { value: "	60	", text: "Czech	" },
  { value: "	61	", text: "Danish	" },
  { value: "	62	", text: "Djiboutian	" },
  { value: "	63	", text: "Dominican	" },
  { value: "	64	", text: "Dutch	" },
  { value: "	65	", text: "East Timorese	" },
  { value: "	66	", text: "Ecuadorean	" },
  { value: "	67	", text: "Egyptian	" },
  { value: "	68	", text: "Emirati	" },
  { value: "	69	", text: "English	" },
  { value: "	70	", text: "Equatorial Guinean	" },
  { value: "	71	", text: "Eritrean	" },
  { value: "	72	", text: "Estonian	" },
  { value: "	73	", text: "Ethiopian	" },
  { value: "	74	", text: "Faroese	" },
  { value: "	75	", text: "Fijian	" },
  { value: "	76	", text: "Filipino	" },
  { value: "	77	", text: "Finnish	" },
  { value: "	78	", text: "French	" },
  { value: "	79	", text: "Gabonese	" },
  { value: "	80	", text: "Gambian	" },
  { value: "	81	", text: "Georgian	" },
  { value: "	82	", text: "German	" },
  { value: "	83	", text: "Ghanaian	" },
  { value: "	84	", text: "Gibraltarian	" },
  { value: "	85	", text: "Greek	" },
  { value: "	86	", text: "Greenlandic	" },
  { value: "	87	", text: "Grenadian	" },
  { value: "	88	", text: "Guamanian	" },
  { value: "	89	", text: "Guatemalan	" },
  { value: "	90	", text: "Guinean	" },
  { value: "	91	", text: "Guyanese	" },
  { value: "	92	", text: "Haitian	" },
  { value: "	93	", text: "Honduran	" },
  { value: "	94	", text: "Hong Konger	" },
  { value: "	95	", text: "Hungarian	" },
  { value: "	96	", text: "Icelandic	" },
  { value: "	97	", text: "Indian	" },
  { value: "	98	", text: "Indonesian	" },
  { value: "	99	", text: "Iranian	" },
  { value: "	100	", text: "Iraqi	" },
  { value: "	101	", text: "Irish	" },
  { value: "	102	", text: "Israeli	" },
  { value: "	103	", text: "Italian	" },
  { value: "	104	", text: "Ivorian	" },
  { value: "	105	", text: "Jamaican	" },
  { value: "	106	", text: "Japanese	" },
  { value: "	107	", text: "Jordanian	" },
  { value: "	108	", text: "Kazakh	" },
  { value: "	109	", text: "Kenyan	" },
  { value: "	110	", text: "Kittitian	" },
  { value: "	111	", text: "Kosovan	" },
  { value: "	112	", text: "Kuwaiti	" },
  { value: "	113	", text: "Kyrgyz	" },
  { value: "	114	", text: "Lao	" },
  { value: "	115	", text: "Latvian	" },
  { value: "	116	", text: "Lebanese	" },
  { value: "	117	", text: "Liberian	" },
  { value: "	118	", text: "Libyan	" },
  { value: "	119	", text: "Liechtenstein citizen	" },
  { value: "	120	", text: "Lithuanian	" },
  { value: "	121	", text: "Luxembourger	" },
  { value: "	122	", text: "Macanese	" },
  { value: "	123	", text: "Macedonian	" },
  { value: "	124	", text: "Malagasy	" },
  { value: "	125	", text: "Malawian	" },
  { value: "	126	", text: "Malaysian	" },
  { value: "	127	", text: "Maldivian	" },
  { value: "	128	", text: "Malian	" },
  { value: "	129	", text: "Maltese	" },
  { value: "	130	", text: "Marshallese	" },
  { value: "	131	", text: "Martiniquais	" },
  { value: "	132	", text: "Mauritanian	" },
  { value: "	133	", text: "Mauritian	" },
  { value: "	134	", text: "Mexican	" },
  { value: "	135	", text: "Micronesian	" },
  { value: "	136	", text: "Moldovan	" },
  { value: "	137	", text: "Monegasque	" },
  { value: "	138	", text: "Mongolian	" },
  { value: "	139	", text: "Montenegrin	" },
  { value: "	140	", text: "Montserratian	" },
  { value: "	141	", text: "Moroccan	" },
  { value: "	142	", text: "Mosotho	" },
  { value: "	143	", text: "Mozambican	" },
  { value: "	144	", text: "Namibian	" },
  { value: "	145	", text: "Nauruan	" },
  { value: "	146	", text: "Nepalese	" },
  { value: "	147	", text: "New Zealander	" },
  { value: "	148	", text: "Nicaraguan	" },
  { value: "	149	", text: "Nigerian	" },
  { value: "	150	", text: "Nigerien	" },
  { value: "	151	", text: "Niuean	" },
  { value: "	152	", text: "North Korean	" },
  { value: "	153	", text: "Northern Irish	" },
  { value: "	154	", text: "Norwegian	" },
  { value: "	155	", text: "Omani	" },
  { value: "	156	", text: "Pakistani	" },
  { value: "	157	", text: "Palauan	" },
  { value: "	158	", text: "Palestinian	" },
  { value: "	159	", text: "Panamanian	" },
  { value: "	160	", text: "Papua New Guinean	" },
  { value: "	161	", text: "Paraguayan	" },
  { value: "	162	", text: "Peruvian	" },
  { value: "	163	", text: "Pitcairn Islander	" },
  { value: "	164	", text: "Polish	" },
  { value: "	165	", text: "Portuguese	" },
  { value: "	166	", text: "Prydeinig	" },
  { value: "	167	", text: "Puerto Rican	" },
  { value: "	168	", text: "Qatari	" },
  { value: "	169	", text: "Romanian	" },
  { value: "	170	", text: "Russian	" },
  { value: "	171	", text: "Rwandan	" },
  { value: "	172	", text: "Salvadorean	" },
  { value: "	173	", text: "Sammarinese	" },
  { value: "	174	", text: "Samoan	" },
  { value: "	175	", text: "Sao Tomean	" },
  { value: "	176	", text: "Saudi Arabian	" },
  { value: "	177	", text: "Scottish	" },
  { value: "	178	", text: "Senegalese	" },
  { value: "	179	", text: "Serbian	" },
  { value: "	180	", text: "Sierra Leonean	" },
  { value: "	181	", text: "Singaporean	" },
  { value: "	182	", text: "Slovak	" },
  { value: "	183	", text: "Slovenian	" },
  { value: "	184	", text: "Solomon Islander	" },
  { value: "	185	", text: "Somali	" },
  { value: "	186	", text: "South African	" },
  { value: "	187	", text: "South Korean	" },
  { value: "	188	", text: "South Sudanese	" },
  { value: "	189	", text: "Spanish	" },
  { value: "	190	", text: "Sri Lankan	" },
  { value: "	191	", text: "St Helenian	" },
  { value: "	192	", text: "St Lucian	" },
  { value: "	193	", text: "Stateless	" },
  { value: "	194	", text: "Sudanese	" },
  { value: "	195	", text: "Surinamese	" },
  { value: "	196	", text: "Swazi	" },
  { value: "	197	", text: "Swedish	" },
  { value: "	198	", text: "Swiss	" },
  { value: "	199	", text: "Syrian	" },
  { value: "	200	", text: "Taiwanese	" },
  { value: "	201	", text: "Tajik	" },
  { value: "	202	", text: "Tanzanian	" },
  { value: "	203	", text: "Thai	" },
  { value: "	204	", text: "Togolese	" },
  { value: "	205	", text: "Tongan	" },
  { value: "	206	", text: "Trinidadian	" },
  { value: "	207	", text: "Tristanian	" },
  { value: "	208	", text: "Tunisian	" },
  { value: "	209	", text: "Turkish	" },
  { value: "	210	", text: "Turkmen	" },
  { value: "	211	", text: "Turks and Caicos Islander	" },
  { value: "	212	", text: "Tuvaluan	" },
  { value: "	213	", text: "Ugandan	" },
  { value: "	214	", text: "Ukrainian	" },
  { value: "	215	", text: "Uruguayan	" },
  { value: "	216	", text: "Uzbek	" },
  { value: "	217	", text: "Vatican citizen	" },
  { value: "	218	", text: "Venezuelan	" },
  { value: "	219	", text: "Vietnamese	" },
  { value: "	220	", text: "Vincentian	" },
  { value: "	221	", text: "Wallisian	" },
  { value: "	222	", text: "Welsh	" },
  { value: "	223	", text: "Yemeni	" },
  { value: "	224	", text: "Zambian	" },
  { value: "	225	", text: "Zimbabwean	" },
];

export const titles = () => [
  { value: "1", text: "Mr" },
  { value: "2", text: "Mrs" },
  { value: "3", text: "Ms" },
  { value: "4", text: "Miss" },
  { value: "5", text: "Dr" },
  { value: "6", text: "Rev" },
  { value: "7", text: "Prof" },
  { value: "8", text: "Venerable" },
];

export const province = () => [
  { value: "1", text: "Central Province" },
  { value: "2", text: "Eastern Province" },
  { value: "3", text: "Northern Province" },
  { value: "4", text: "Southern Province " },
  { value: "5", text: "Western Province" },
  { value: "6", text: "North Western Province" },
  { value: "7", text: "North Central Province" },
  { value: "8", text: "Uva Province " },
  { value: "9", text: "Sabaragamuwa Province" },
];

export const countries = () => [
  { value: "1", text: "Sri Lanka" },
  { value: "2", text: "China" },
  { value: "3", text: "India" },
  { value: "4", text: "United States" },
  { value: "5", text: "Indonesia" },
  { value: "6", text: "Pakistan" },
  { value: "7", text: "Brazil" },
];

export const sex = () => [
  { value: "1", text: "Female" },
  { value: "2", text: "Male" },
];

export const userStatus = () => [
  { value: "1", text: "New User" },
  { value: "2", text: "Active" },
  { value: "3", text: "Password Reset" },
  { value: "4", text: "Auto Inactive" },
  { value: "5", text: "Inactive" },
];
export const userType = () => [
  { value: "1", text: "SuperUser" },
  { value: "2", text: "Admin" },
  { value: "3", text: "User" },
];
